swagger: '2.0'
info:
  title: ImageAI
  description: ''
  version: ''
host: '127.0.0.1:8000'

paths:
  /documentation:
    get:
      operationId: documentation_list
      responses:
        '200':
          description: ''
      parameters: []
      tags:
        - documentation
  /login/:
    post:
      operationId: login_create
      responses:
        '201':
          description: ''
      parameters:
        - name: data
          in: body
          schema:
            type: object
            properties:
              username:
                description: ''
                type: string
              password:
                description: ''
                type: string
            required:
              - username
              - password
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      summary: Takes a set of user credentials and returns an access and refresh JSON web
      consumes:
        - application/json
      tags:
        - login
  /post/:
    post:
      operationId: post_create
      responses:
        '201':
          description: ''
      parameters: []
      tags:
        - post
  '/profile/{profile_id}/update/':
    put:
      operationId: profile_update_update
      responses:
        '200':
          description: ''
      parameters:
        - name: profile_id
          required: true
          in: path
          description: ''
          type: string
        - name: data
          in: body
          schema:
            type: object
            properties:
              subscribed:
                description: ''
                type: boolean
              limit:
                description: ''
                type: integer
              key:
                description: ''
                type: string
      consumes:
        - application/json
      tags:
        - profile
    patch:
      operationId: profile_update_partial_update
      responses:
        '200':
          description: ''
      parameters:
        - name: profile_id
          required: true
          in: path
          description: ''
          type: string
        - name: data
          in: body
          schema:
            type: object
            properties:
              subscribed:
                description: ''
                type: boolean
              limit:
                description: ''
                type: integer
              key:
                description: ''
                type: string
      consumes:
        - application/json
      tags:
        - profile
  /register/:
    post:
      operationId: register_create
      responses:
        '201':
          description: ''
      parameters:
        - name: data
          in: body
          schema:
            type: object
            properties:
              username:
                description: 'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'
                type: string
              password:
                description: ''
                type: string
              first_name:
                description: ''
                type: string
              last_name:
                description: ''
                type: string
              email:
                description: ''
                type: string
            required:
              - username
              - password
      consumes:
        - application/json
      tags:
        - register


